language: python
python:
- '3.5'
sudo: required
services:
- docker
branches:
  only:
  - sources
env:
  global:
  - secure: "bAHWTnuavAetVZOWw+ze2sKNYz8v1mV04NQEp83wnGMIuWRIDBSFMgf29hdKd47NHD/3Jw5yfLq0XcnvQDMB5YWYhCCT+L7QNNi6+LCcvxujEIXPjcc96i5X4lnk6lU9hS32CS+P8Xex4x2kZv+TO3KY9egQSHfGmRRDhIRVgGU="
install:
- pip install ghp-import
- git clone https://github.com/getpelican/pelican-plugins
script:
- make publish github
