language: python
python:
- '3.5'
sudo: required
services:
- docker
branches:
  only:
  - sources
env:
  global:
  - secure: "CLYWAWWMUOG0ZVmsmt3Qk840p+JBN/CU2MWOHWyRabB7UYBo3FQtf4JAMsm0AaSIAThAZzn07hpAeq/6vHG1BTqqd8DE92/scd56bUxZBHxhqKaLnnct/YpklAyi/B1h8prb+KcyN8t2Qs6s9t6Ber8ea69EeJm7hOIT/6M+HSs="
install:
- pip install ghp-import
- git clone https://github.com/getpelican/pelican-plugins
script:
- make publish github
